minimum_pre_commit_version: "2.5.1"
# default_stages: [commit, push]
# fail_fast: true
repos:
  # Git-related
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: forbid-new-submodules
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      - id: git-dirty

  # Reformatting (should generally come before any file format or other checks, because reformatting can change things)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys]
        exclude: sample_waveform_data/|jsdoc.json|.babelrc

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
        # args: [--vue-indent-script-and-style true]
        exclude: sample_waveform_data/|dist/|jsdoc.json

  # Safety/Security Issues
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: detect-private-key

  # Invalid File Checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
        name: general-large-file-check
        args: ["--maxkb=123"]
        exclude: package-lock.json|tests/sample_waveform_data/mantarray/|dist
      - id: check-json
      - id: check-yaml
      - id: check-xml
      - id: check-merge-conflict
      - id: check-case-conflict
  # Linting
  - repo: https://github.com/NanoSurface-Biomedical/pre-commit-pylint
    rev: "c0d03fa500201c43aebf0640253b89c89cec9937" # pick a git hash / tag to point to
    hooks:
      - id: vuejs-check-no-console-log-statments
        exclude: dist
      - id: vuejs-check-no-import-from-vue-file
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.23.0
    hooks:
      - id: eslint
        exclude: (dist/)|(tests/unit/components/status/StatusBar.spec.js)|(tests/unit/components/status/SimulationMode.spec.js)|(tests/unit/components/playback/ContinuousWaveform.spec.js)|(tests/unit/components/playback/controls/WebPlayerControls.spec.js)|(tests/unit/components/playback/controls/YAxisControls.spec.js)|(tests/unit/components/playback/controls/PlateBarcode.spec.js)|(tests/unit/components/plate_based_widgets/navigator/PlateNavigator.spec.js)|(tests/unit/components/playback/controls/DesktopPlayerControls.spec.js)|(tests/unit/components/playback/controls/XAxisControls.spec.js)|(tests/e2e/)|(server.js)
        files: \.(vue)|(js)$
        types: [file]
        args: [--fix]
