AWSTemplateFormatVersion: 2010-09-09
Transform: "AWS::Serverless-2016-10-31"

# Adapted from: https://github.com/aws-samples/aws-codebuild-samples/blob/master/cloudformation/continuous-integration-pull-request-checks.yml

# Note (Eli 5/3/30): you must connect your AWS account to your github account using OAuth manually before this will work (one-time). To do so, just attempt to create a CodeBuild project through the console--you don't need to finish creating it, just get to the point where you've created the OAuth connection.

# to create: aws cloudformation deploy --stack-name=codebuild-mantarray-frontend-components-publish-to-npm --parameter-overrides GithubRepoName=mantarray-frontend-components ArtifactsBucketName=build-artifacts-x92toe --template-file=codebuild-formation.yaml --capabilities CAPABILITY_NAMED_IAM

Description: Use CodeBuild to publish Github repos to PyPi using company PyPi credentials

Parameters:
  GithubRepoName:
    Description: A Github repository that contains the application code.
    Type: String
  ArtifactsBucketName:
    Description: An S3 bucket to place build artifacts. Must be in same region as this stack.
    Type: String

Resources:
  CodeBuildPolicy:
    Description: Setting IAM policy for service role for CodeBuild
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource: "*"
          - Action:
              - s3:PutObject
              - s3:GetBucketAcl
              - s3:GetBucketLocation
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ":"
                  - - "arn"
                    - "aws"
                    - "s3"
                    - ""
                    - ""
                    - Ref: "ArtifactsBucketName"
              - Fn::Join:
                  - ":"
                  - - "arn"
                    - "aws"
                    - "s3"
                    - ""
                    - ""
                    - Fn::Join:
                        - "/"
                        - - Ref: "ArtifactsBucketName"
                          - "*"
            
          - Action:
              - ssm:GetParameters
            Effect: Allow
            Resource:
              - Fn::Join:
                  - "/"
                  - - "arn:aws:ssm:*:*:parameter/CodeBuild"
                    - "general"
                    - "*"
          - Action:
              - kms:Decrypt
            Effect: Allow
            Resource: "arn:aws:kms:*:*:alias/aws/ssm"

      PolicyName:
        Fn::Join:
          - "-"
          - - Ref: "AWS::StackName"
            - CodeBuildPolicy
      Roles:
        - Ref: "CodeBuildRole"
    Type: AWS::IAM::Policy

  CodeBuildProject:
    DependsOn:
      - CodeBuildPolicy
    Properties:
      Artifacts:
        Location:
          Ref: "ArtifactsBucketName"
        Packaging: ZIP
        OverrideArtifactName: true # This is equivalent to checking the "Enable Semantic Versioning" box in the console
        Type: S3
      BadgeEnabled: true
      Description:
        Fn::Join:
          - ""
          - - "CodeBuild Project for "
            - Ref: "AWS::StackName"
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:4.0-20.08.14
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: PUBLISH_TO_NPM
            Type: PLAINTEXT
            Value: "0"

      Name:
        Fn::Join:
          - "-"
          - - Ref: GithubRepoName
            - "publish-to-npm"
      ServiceRole:
        Ref: "CodeBuildRole"
      Source:
        Auth:
          Type: "OAUTH"
        GitCloneDepth: 1

        ReportBuildStatus: True
        Location:
          Fn::Join:
            - ""
            - - "https://github.com/CuriBio/"
              - Ref: GithubRepoName
              - "/"
        Type: GITHUB

      QueuedTimeoutInMinutes: 10
      TimeoutInMinutes: 30
    Type: AWS::CodeBuild::Project

  CodeBuildRole:
    Description: Creating service role in IAM for AWS CodeBuild
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
      Path: /
      RoleName:
        Fn::Join:
          - "-"
          - - Ref: "AWS::StackName"
            - CodeBuild
    Type: AWS::IAM::Role
